# -*- coding: utf-8 -*-
"""Copy of Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YpuqrmF3Eu70Pz_YK3kak8f11Hw0llI
"""

import math
Radians60 = math.radians(60)
sin60 = math.sin(Radians60)
sin60Rounded = round(sin60,2)
Radians90 = math.radians(90)
tan90 = math.tan(Radians90)
tan90Rounded = round(tan90,2)
print(" Sin60:{} ".format(sin60Rounded))
print(" tan90:{} ".format(tan90Rounded))