# -*- coding: utf-8 -*-
"""Copy of Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrXYBHITNTw-Ar2wRgPSpzc96dIjezVD
"""

import random 
test_list =[100,1,2,3,30,40,"hi","hello"] 
 print ("The original list is : " + str(test_list)) 
random.shuffle(test_list)  
print ("The shuffled list is : " +  str(test_list))