# -*- coding: utf-8 -*-
"""Copy of Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0aMaywwAHBb9bD0AIQCEUsi1PDs4g5M
"""

from math import tan, pi
n_sides = int(input("The  number of sides: "))
s_length = float(input(" The length of a side: "))
p_area = n_sides * (s_length ** 2) / (4 * tan(pi / n_sides))
print("The area of the polygon is: ",p_area)