# -*- coding: utf-8 -*-
"""Copy of Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e9mFhKy7UQpc4gX_VB21f89syiFy29H
"""

import math
r = float(input("Enter Radius of the circle "))
area = math.pi* r * r
print("%.2f" %area)