# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JiIAtK7hFZzbyvtC6z34F9kZ0gkSk73P
"""

import math 
 
pi = 3.14159
 
 
def area_of_segment(radius, angle): 
 
    # Calculating area of sector 
 
    area_of_sector = pi * (radius * radius)  * (angle / 360) 
 
  
 
    # Calculating area of triangle 
 
    area_of_triangle = 1 / 2 *  (radius * radius) *math.sin((angle * pi) / 180) 
 
  
 
    return area_of_sector - area_of_triangle; 
 
 
radius = 20.0
 
angle =80.0
 
print("The Area of minor segment =", area_of_segment(radius, angle)) 
 
print("The Area of major segment =",area_of_segment(radius, (360 - angle)))